# Generated by Django 5.0b1 on 2023-11-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('workspace_type', models.CharField(max_length=50)),
                ('days_available', models.CharField(max_length=50)),
                ('time_start', models.TimeField()),
                ('end_start', models.TimeField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
