# Generated by Django 5.0b1 on 2023-11-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workspace',
            table='Workspace',
        ),
    ]
